### ISSUE TITLE
npz文件

### ISSUE THREAD

**Issue by zouyunpeng666** [openai/guided-diffusion#116]
采样生成的图像保存为npz文件，我想知道该怎么将npz文件还原成图片呢

**Comment by zouyunpeng666** [comment]
data= np.load('samples_10x64x64x3.npz')
k = 0
for i in data['arr_0']:
    if k%1000==0:
        print(k)
    img = Image.fromarray(i)
    img.save(str(k)+".jpg")
    k = k+1

**Comment by zouyunpeng666** [comment]
import numpy as np

from PIL import Image
data= np.load('samples_10x64x64x3.npz')
k = 0
for i in data['arr_0']:
    img = Image.fromarray(i)
    img.save(str(k)+".jpg")
    k = k+1

**Comment by wang1528186571** [comment]
> import numpy as np
> 
> from PIL import Image data= np.load('samples_10x64x64x3.npz') k = 0 for i in data['arr_0']: img = Image.fromarray(i) img.save(str(k)+".jpg") k = k+1

我遇到了这个问题是为什么？
Traceback (most recent call last):
  File "/home/wang/Desktop/wjl-project/improved-diffusion-main/iamge.py", line 7, in <module>
    for i in data['arr_0']:
  File "/home/wang/Anaconda3/envs/diffusion/lib/python3.8/site-packages/numpy/lib/npyio.py", line 260, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'arr_0 is not a file in the archive'
